build:
  type: dockerfile
  config:
    dockerfile: Dockerfile
    context: .

deploy:
  resources:
    memory: 512Mi
    cpu: 500m
  port: 80
  env:
    - name: REACT_APP_API_URL
      value: http://escritor-api:8000
    - name: NODE_ENV
      value: production
  healthCheck:
    path: /
    port: 80
  volumes: []
