build:
  type: dockerfile
  config:
    dockerfile: Dockerfile
    context: .
    target: production

deploy:
  resources:
    memory: 512Mi
    cpu: 500m
  port: 80
  env:
    - name: REACT_APP_API_URL
      value: http://escritor-backend:8000
  healthCheck:
    path: /
    port: 80
  volumes: []
